# Cloudflare Pages project configuration
# This project uses Cloudflare Pages with Functions, not standalone Workers
# Deploy via Cloudflare Pages dashboard or 'wrangler pages publish'

name = "multi-agent-conversation-generator"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

# Build configuration for Cloudflare Pages
[build]
command = "npm run build"

# Environment configurations for different stages
[env.production]
name = "multi-agent-conversation-generator"

[env.staging] 
name = "multi-agent-conversation-generator-staging"

# Note: Environment variables like OPENAI_API_KEY should be set in the Cloudflare Pages dashboard