name = "multicahtbackend"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

# Environment variables will be set in the Cloudflare dashboard
# OPENAI_API_KEY = "your-key-here"  # Set this in the dashboard

[[env.staging]]
name = "multicahtbackend-staging"

[[env.production]]
name = "multicahtbackend"