name = "multi-agent-conversation-generator"
main = "functions/index.ts"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
destination = "dist"

[vars]
ENVIRONMENT = "production"

# Environment variables will be set in the Cloudflare dashboard
# OPENAI_API_KEY = "your-key-here"  # Set this in the dashboard

[[env.staging]]
name = "multi-agent-conversation-generator-staging"

[[env.production]]
name = "multi-agent-conversation-generator"